test deployment

diff --git a/.github/workflows/github-pipeline.yml b/.github/workflows/github-pipeline.yml
--- a/.github/workflows/github-pipeline.yml
+++ b/.github/workflows/github-pipeline.yml
@@ -9,9 +9,8 @@ on:
       - main
 
 jobs:
-  build:
+  build_and_deploy:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout source code
         uses: actions/checkout@v2
@@ -23,17 +22,28 @@ jobs:
           distribution: 'adopt'
 
       - name: Build with Maven
-        run: mvn -B package --file pom.xml
+        run: |
+          mvn -B package --file pom.xml
+          mvn_result=$?
+          if [ $mvn_result -ne 0 ]; then
+            echo "Maven build failed with exit code $mvn_result"
+            exit $mvn_result
+          fi
 
       - name: Run Unit Tests
         run: mvn test --file pom.xml
 
       - name: Install zip
-        run: sudo apt-get install zip
+        run: apt-get update && apt-get install -y zip
 
       - name: Create deployment package
         run: |
           zip -r deploy.zip . -x '*.git*'
+          if [ ! -f "deploy.zip" ]; then
+            echo "Failed to create deployment package."
+            exit 1
+          fi
+
       - name: Deploy to EB
         uses: einaregilsson/beanstalk-deploy@v21
         with:
